import Head from 'next/head'
import { useState } from 'react'
import Header from '../components/Header'
import Main from '../components/Main'
import { getAllMutualPaths, getShortestPath } from '../utils/map'
import { createNetwork } from '../utils/network'
import { initializeUsers } from '../utils/users'

export default function Home() {
  const [users, setUsers] = useState(initializeUsers)

  return (
    <>
      <div className='h-screen bg-gray-200 dark:bg-[#001523] overflow-hidden'>
        <Head>
          <title>SocialBook</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/logo.svg' />
        </Head>

        <Header />

        <Main users={users} setUsers={setUsers} />
      </div>
    </>
  )
}
